# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: dart test
      - name: Dart/Flutter Package Analyzer
        # You may pin to the exact commit or the version.
        # uses: axel-op/dart-package-analyzer@7a6c3c66bce78d82b729a1ffef2d9458fde6c8d2
        uses: axel-op/dart-package-analyzer@v3
        with:
          # Token to connect to GitHub. Use secrets.GITHUB_TOKEN
          githubToken: secrets.GITHUB_TOKEN
